@PayrollPractice.Api_HostAddress = https://localhost:7167

### Create a New Employee
POST {{PayrollPractice.Api_HostAddress}}/api/employee
Content-Type: application/json

{
  "name": "Weyehn Reeves",
  "hourlyRate": 35.50,
  "departmentId": 2,
  "birthDate": "1995-04-12",
  "startDate": "2026-06-01"
}

